/**
 * Oil India Limited - Baghewala Field Multi-Well Registry (23 Wells)
 * Jodhpur Sandstone Heavy Oil Development, Rajasthan
 * All values declare parameter-level provenance.
 */

import { WellOverview } from "../types/twin";

export const BAGHEWALA_FIELD_WELLS: WellOverview[] = [
  {
    wellId: "BGW-01",
    wellName: "BGW-01",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1056, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 15.1, unit: "°API", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 95, instrumentOrObserver: "Laboratory Assay" },
    currentCycle: 3,
    currentDay: 14,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 118.4, unit: "°C", source: "ESTIMATED", confidencePercent: 94, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 410, unit: "cP", source: "ESTIMATED", confidencePercent: 92, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 14,
    productionBopd: { value: 740, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 94,
    latitude: 27.8124,
    longitude: 72.4182,
  },
  {
    wellId: "BGW-02",
    wellName: "BGW-02",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1197, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 14.0, unit: "°API", source: "SCENARIO", confidencePercent: 90, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 5,
    currentDay: 32,
    phase: "COOLING",
    status: "WARNING",
    bhtCelsius: { value: 58.2, unit: "°C", source: "ESTIMATED", confidencePercent: 88, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 7450, unit: "cP", source: "ESTIMATED", confidencePercent: 86, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 58,
    productionBopd: { value: 410, unit: "BOPD", source: "MEASURED", confidencePercent: 96, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 88,
    latitude: 27.8145,
    longitude: 72.4215,
  },
  {
    wellId: "BGW-03",
    wellName: "BGW-03",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1184, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 15.9, unit: "°API", source: "SCENARIO", confidencePercent: 92, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 2,
    currentDay: 4,
    phase: "CYCLE_END",
    status: "HEALTHY",
    bhtCelsius: { value: 39.5, unit: "°C", source: "ESTIMATED", confidencePercent: 96, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 15400, unit: "cP", source: "ESTIMATED", confidencePercent: 94, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 5,
    productionBopd: { value: 0, unit: "BOPD", source: "MEASURED", confidencePercent: 99, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 96,
    latitude: 27.8168,
    longitude: 72.4165,
  },
  {
    wellId: "BGW-04",
    wellName: "BGW-04",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1091, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.4, unit: "°API", source: "SCENARIO", confidencePercent: 89, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 4,
    currentDay: 39,
    phase: "COOLING",
    status: "CRITICAL",
    bhtCelsius: { value: 44.1, unit: "°C", source: "ESTIMATED", confidencePercent: 82, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 14200, unit: "cP", source: "ESTIMATED", confidencePercent: 81, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 88,
    productionBopd: { value: 185, unit: "BOPD", source: "MEASURED", confidencePercent: 95, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 82,
    latitude: 27.8095,
    longitude: 72.4251,
  },
  {
    wellId: "BGW-05",
    wellName: "BGW-05",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1261, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 15.1, unit: "°API", source: "SCENARIO", confidencePercent: 91, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 6,
    currentDay: 8,
    phase: "SOAK",
    status: "HEALTHY",
    bhtCelsius: { value: 189.5, unit: "°C", source: "ESTIMATED", confidencePercent: 95, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 52, unit: "cP", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 6,
    productionBopd: { value: 0, unit: "BOPD", source: "MEASURED", confidencePercent: 99, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 95,
    latitude: 27.8182,
    longitude: 72.4289,
  },
  {
    wellId: "BGW-06",
    wellName: "BGW-06",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1112, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 15.3, unit: "°API", source: "SCENARIO", confidencePercent: 92, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 4,
    currentDay: 19,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 98.6, unit: "°C", source: "ESTIMATED", confidencePercent: 92, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 1120, unit: "cP", source: "ESTIMATED", confidencePercent: 90, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 22,
    productionBopd: { value: 620, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 92,
    latitude: 27.8111,
    longitude: 72.4132,
  },
  {
    wellId: "BGW-07",
    wellName: "BGW-07",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1199, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.0, unit: "°API", source: "SCENARIO", confidencePercent: 90, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 3,
    currentDay: 26,
    phase: "PRODUCTION",
    status: "WARNING",
    bhtCelsius: { value: 71.0, unit: "°C", source: "ESTIMATED", confidencePercent: 89, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 6100, unit: "cP", source: "ESTIMATED", confidencePercent: 87, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 61,
    productionBopd: { value: 490, unit: "BOPD", source: "MEASURED", confidencePercent: 96, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 89,
    latitude: 27.8139,
    longitude: 72.4312,
  },
  {
    wellId: "BGW-08",
    wellName: "BGW-08",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1293, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 16.5, unit: "°API", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 96, instrumentOrObserver: "Laboratory Assay" },
    currentCycle: 4,
    currentDay: 25,
    phase: "PRODUCTION",
    status: "WARNING",
    bhtCelsius: { value: 74.2, unit: "°C", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 5820, unit: "cP", source: "ESTIMATED", confidencePercent: 91, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 64,
    productionBopd: { value: 560, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 93,
    latitude: 27.8155,
    longitude: 72.4201,
  },
  {
    wellId: "BGW-09",
    wellName: "BGW-09",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1065, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 18.7, unit: "°API", source: "SCENARIO", confidencePercent: 93, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 1,
    currentDay: 11,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 145.0, unit: "°C", source: "ESTIMATED", confidencePercent: 95, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 180, unit: "cP", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 9,
    productionBopd: { value: 810, unit: "BOPD", source: "MEASURED", confidencePercent: 98, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 95,
    latitude: 27.8078,
    longitude: 72.4174,
  },
  {
    wellId: "BGW-10",
    wellName: "BGW-10",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1228, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.4, unit: "°API", source: "SCENARIO", confidencePercent: 88, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 5,
    currentDay: 43,
    phase: "CYCLE_END",
    status: "CRITICAL",
    bhtCelsius: { value: 38.2, unit: "°C", source: "ESTIMATED", confidencePercent: 81, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 16800, unit: "cP", source: "ESTIMATED", confidencePercent: 80, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 94,
    productionBopd: { value: 65, unit: "BOPD", source: "MEASURED", confidencePercent: 94, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 81,
    latitude: 27.8201,
    longitude: 72.4234,
  },
  {
    wellId: "BGW-11",
    wellName: "BGW-11",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1068, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.3, unit: "°API", source: "SCENARIO", confidencePercent: 91, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 2,
    currentDay: 18,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 104.2, unit: "°C", source: "ESTIMATED", confidencePercent: 91, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 850, unit: "cP", source: "ESTIMATED", confidencePercent: 89, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 19,
    productionBopd: { value: 670, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 91,
    latitude: 27.8166,
    longitude: 72.4345,
  },
  {
    wellId: "BGW-12",
    wellName: "BGW-12",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1065, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 18.0, unit: "°API", source: "SCENARIO", confidencePercent: 89, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 4,
    currentDay: 29,
    phase: "COOLING",
    status: "WARNING",
    bhtCelsius: { value: 66.8, unit: "°C", source: "ESTIMATED", confidencePercent: 87, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 6800, unit: "cP", source: "ESTIMATED", confidencePercent: 85, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 67,
    productionBopd: { value: 440, unit: "BOPD", source: "MEASURED", confidencePercent: 96, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 87,
    latitude: 27.8089,
    longitude: 72.4287,
  },
  {
    wellId: "BGW-13",
    wellName: "BGW-13",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1282, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 14.8, unit: "°API", source: "SCENARIO", confidencePercent: 92, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 5,
    currentDay: 3,
    phase: "INJECTION",
    status: "HEALTHY",
    bhtCelsius: { value: 165.0, unit: "°C", source: "ESTIMATED", confidencePercent: 95, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 78, unit: "cP", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 5,
    productionBopd: { value: 0, unit: "BOPD", source: "MEASURED", confidencePercent: 99, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 93,
    latitude: 27.8062,
    longitude: 72.4195,
  },
  {
    wellId: "BGW-14",
    wellName: "BGW-14",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1089, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 18.8, unit: "°API", source: "SCENARIO", confidencePercent: 94, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 3,
    currentDay: 21,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 89.2, unit: "°C", source: "ESTIMATED", confidencePercent: 91, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 1450, unit: "cP", source: "ESTIMATED", confidencePercent: 89, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 26,
    productionBopd: { value: 590, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 86,
    latitude: 27.8055,
    longitude: 72.4228,
  },
  {
    wellId: "BGW-15",
    wellName: "BGW-15",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1151, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 16.8, unit: "°API", source: "SCENARIO", confidencePercent: 88, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 4,
    currentDay: 44,
    phase: "CYCLE_END",
    status: "CRITICAL",
    bhtCelsius: { value: 37.0, unit: "°C", source: "ESTIMATED", confidencePercent: 80, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 17500, unit: "cP", source: "ESTIMATED", confidencePercent: 79, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 95,
    productionBopd: { value: 0, unit: "BOPD", source: "MEASURED", confidencePercent: 99, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 45,
    latitude: 27.8071,
    longitude: 72.4265,
  },
  {
    wellId: "BGW-16",
    wellName: "BGW-16",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1129, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 14.4, unit: "°API", source: "SCENARIO", confidencePercent: 89, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 2,
    currentDay: 17,
    phase: "PRODUCTION",
    status: "WARNING",
    bhtCelsius: { value: 106.8, unit: "°C", source: "ESTIMATED", confidencePercent: 90, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 3200, unit: "cP", source: "ESTIMATED", confidencePercent: 88, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 41,
    productionBopd: { value: 480, unit: "BOPD", source: "MEASURED", confidencePercent: 96, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 79,
    latitude: 27.8048,
    longitude: 72.4310,
  },
  {
    wellId: "BGW-17",
    wellName: "BGW-17",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1203, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.3, unit: "°API", source: "SCENARIO", confidencePercent: 93, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 1,
    currentDay: 12,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 138.5, unit: "°C", source: "ESTIMATED", confidencePercent: 95, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 240, unit: "cP", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 11,
    productionBopd: { value: 720, unit: "BOPD", source: "MEASURED", confidencePercent: 98, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 95,
    latitude: 27.8068,
    longitude: 72.4352,
  },
  {
    wellId: "BGW-18",
    wellName: "BGW-18",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1101, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 15.3, unit: "°API", source: "SCENARIO", confidencePercent: 91, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 3,
    currentDay: 22,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 84.5, unit: "°C", source: "ESTIMATED", confidencePercent: 90, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 2150, unit: "cP", source: "ESTIMATED", confidencePercent: 88, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 32,
    productionBopd: { value: 530, unit: "BOPD", source: "MEASURED", confidencePercent: 96, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 82,
    latitude: 27.8082,
    longitude: 72.4385,
  },
  {
    wellId: "BGW-19",
    wellName: "BGW-19",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1190, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 18.7, unit: "°API", source: "SCENARIO", confidencePercent: 92, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 2,
    currentDay: 15,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 112.0, unit: "°C", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 520, unit: "cP", source: "ESTIMATED", confidencePercent: 91, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 16,
    productionBopd: { value: 650, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 90,
    latitude: 27.8175,
    longitude: 72.4380,
  },
  {
    wellId: "BGW-20",
    wellName: "BGW-20",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1103, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 14.5, unit: "°API", source: "SCENARIO", confidencePercent: 88, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 5,
    currentDay: 37,
    phase: "COOLING",
    status: "CRITICAL",
    bhtCelsius: { value: 48.0, unit: "°C", source: "ESTIMATED", confidencePercent: 83, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 12800, unit: "cP", source: "ESTIMATED", confidencePercent: 82, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 82,
    productionBopd: { value: 210, unit: "BOPD", source: "MEASURED", confidencePercent: 95, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 48,
    latitude: 27.8198,
    longitude: 72.4362,
  },
  {
    wellId: "BGW-21",
    wellName: "BGW-21",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1251, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 18.1, unit: "°API", source: "SCENARIO", confidencePercent: 91, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 3,
    currentDay: 20,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 92.4, unit: "°C", source: "ESTIMATED", confidencePercent: 91, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 1240, unit: "cP", source: "ESTIMATED", confidencePercent: 89, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 24,
    productionBopd: { value: 610, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 89,
    latitude: 27.8215,
    longitude: 72.4318,
  },
  {
    wellId: "BGW-22",
    wellName: "BGW-22",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1150, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 14.3, unit: "°API", source: "SCENARIO", confidencePercent: 93, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 2,
    currentDay: 16,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 108.5, unit: "°C", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 720, unit: "cP", source: "ESTIMATED", confidencePercent: 91, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 18,
    productionBopd: { value: 680, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 93,
    latitude: 27.8188,
    longitude: 72.4140,
  },
  {
    wellId: "BGW-23",
    wellName: "BGW-23",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1136, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 16.2, unit: "°API", source: "SCENARIO", confidencePercent: 95, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 4,
    currentDay: 2,
    phase: "INJECTION",
    status: "HEALTHY",
    bhtCelsius: { value: 176.0, unit: "°C", source: "ESTIMATED", confidencePercent: 96, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 58, unit: "cP", source: "ESTIMATED", confidencePercent: 94, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 4,
    productionBopd: { value: 0, unit: "BOPD", source: "MEASURED", confidencePercent: 99, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 97,
    latitude: 27.8220,
    longitude: 72.4168,
  },
];
